namespace: "default"
app:
  name: "basket"
  port: 6001

replica: 1

dockerImage:
  host: "docker.io/natn2003"
  name: "basketapi"
  version: "latest"
  port: 8080

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "ConnectionStrings__DefaultConnectionString"
    value: "Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true"
  - name: "ConnectionStrings__Redis"
    value: "distributedcache:6379"
  - name: "GrpcSettings__DiscountUrl"
    value: "http://discount-api:6002"
  - name: "MessageBroker__Host"
    value: "amqp://ecommerce-mq:5672"
  - name: "MessageBroker__UserName"
    value: "guest"
  - name: "MessageBroker__Password"
    value: "guest" 