namespace: "default"
app:
  name: "ordering"
  port: 6003

replica: 1

dockerImage:
  host: "docker.io/natn2003"
  name: "orderingapi"
  version: "latest"
  port: 8080

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "ConnectionStrings__DefaultConnectionString"
    value: "Server=orderdb;Database=msdb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
  - name: "MessageBroker__Host"
    value: "amqp://ecommerce-mq:5672"
  - name: "MessageBroker__UserName"
    value: "guest"
  - name: "MessageBroker__Password"
    value: "guest"
  - name: "FeatureManagement__OrderFullfilment"
    value: "false" 