releases:
  - name: blue-volume-claim
    chart: charts/volumeClaim
    values:
      - values/volumeClaim/values.yaml
      - namespace: blue

  - name: blue-external
    chart: charts/external-service
    values:
      - values/external-service/values.yaml
      - namespace: blue
    needs:
      - blue-volume-claim

  - name: blue-catalog-api
    chart: charts/microservice
    values:
      - values/catalog-api/values.yaml
      - namespace: blue
    needs:
      - blue-external

  - name: blue-basket-api
    chart: charts/microservice
    values:
      - values/basket-api/values.yaml
      - namespace: blue
    needs:
      - blue-external

  - name: blue-discount-api
    chart: charts/microservice
    values:
      - values/discount-api/values.yaml
      - namespace: blue
    needs:
      - blue-external

  - name: blue-ordering-api
    chart: charts/microservice
    values:
      - values/ordering-api/values.yaml
      - namespace: blue
    needs:
      - blue-external

  - name: blue-user-api
    chart: charts/microservice
    values:
      - values/user-api/values.yaml
      - namespace: blue
    needs:
      - blue-external
    
  # - name: loadbalancer
  #   chart: charts/loadbalancer
  #   needs:
  #     - blue-catalog-api
  #     - blue-basket-api
  #     - blue-discount-api
  #     - blue-ordering-api
  #     - blue-user-api

  # - name: ingressrule
  #   chart: charts/ingressrule
  #   values:
  #     - values/ingressrule/values.yaml
  #     - namespace: blue
  #   needs:
  #     - blue-catalog-api
  #     - blue-basket-api
  #     - blue-discount-api
  #     - blue-ordering-api
  #     - blue-user-api
