apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api-depl
  labels:
    app: ordering-api_label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api_label
  template:
    metadata:
      labels:
        app: ordering-api_label
    spec:
      containers:
      - name: ordering-api-image
        image: natn2003/orderingapi
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__DefaultConnectionString
          value: "Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
        - name: MessageBroker__Host
          value: "amqp://ecommerce-mq:5672"
        - name: MessageBroker__UserName
          value: "guest"
        - name: MessageBroker__Password
          value: "guest"
        - name: FeatureManagement__OrderFullfilment
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-api
spec:
  selector:
    app: ordering-api_label
  ports:
  - protocol: TCP
    port: 6003
    targetPort: 8080
