namespace: "default"
app:
  name: "discount"
  port: 6002

replica: 1

dockerImage:
  host: "registry.digitalocean.com/microservices-registry-uit"
  name: "discountgrpc"
  version: "latest"
  port: 8080

registrySecret: microservices-registry-uit 

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "ConnectionStrings__DefaultConnectionString"
    value: "Data Source=discountdb" 