namespace: "default"
app:
  name: "user"
  port: 6004

replica: 1

dockerImage:
  host: "docker.io/natn2003"
  name: "userapi"
  version: "latest"
  port: 8080

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "MongoDbConfig__Host"
    value: "mongodb" 