namespace: "default"
app:
  name: "user"
  port: 6004

replica: 1

dockerImage:
  host: "registry.digitalocean.com/microservices-registry-uit"
  name: "userapi"
  version: "latest"
  port: 8080

registrySecret: microservices-registry-uit 

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "MongoDbConfig__Host"
    value: "mongodb" 