namespace: "default"
app:
  name: "catalog"
  port: 6000

replica: 1

dockerImage:
  host: "docker.io/natn2003"
  name: "catalogapi"
  version: "latest"
  port: 8080

envs:
  - name: "ASPNETCORE_HTTP_PORTS"
    value: "8080"
  - name: "ConnectionStrings__DefaultConnectionString"
    value: "Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true" 