apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-api"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: "{{ .Values.app.name }}-label"
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.dockerImage.port }}
